### ISSUE TITLE
Les pages à modifier sur le site sont maquetées

### ISSUE THREAD

**Issue by clemenceprem** [Kozea/www-kozea#100]
- [ ] la présentation des News
- [ ] Notre activité (modification de Kozea platform avec présentation de Promomaker)
- [ ] Modification de Backoffice
- [ ] Modification de KM

**Comment by annabellou** [comment]
Lien avec ceci aussi non ?
https://github.com/Kozea/pellov/issues/122

**Comment by annabellou** [comment]
Je mets ça là
https://github.com/Kozea/pellov/issues/122

**Comment by piline** [comment]
- [ ] la présentation des News -> https://drive.google.com/a/kozea.fr/file/d/0BwBm6Evb-akbT09MNE5meHp6WGM/view?usp=sharing

- [ ] Notre activité (modification de Kozea platform avec présentation de Promomaker)
- [ ] Modification de Backoffice
- [ ] Modification de KM
-> https://drive.google.com/a/kozea.fr/file/d/0BwBm6Evb-akbUFctYnlJTVNHU3M/view?usp=sharing
