### ISSUE TITLE
Le html du www est fait

### ISSUE THREAD

**Issue by clemenceprem** [Kozea/www-kozea#101]
## Backoffice

Fort de son expérience passée dans le tiers-payant, Kozea group a développé Backoffice un ensemble de services dédiés à la gestion du tiers-payant. 

Backoffice regroupe 3 offres :

- Externalisation (renvoi sur le site)
Le professionnel de santé délègue l’ensemble des tâches liées au tiers-payant à un gestionnaire expert Backoffice.

- Formation (renvoi sur le site)
Backoffice propose des formations aux professionnels de santé pour connaître ou approfondir les rouages de la gestion du tiers-payant.

- Gestion en interne (renvoi sur le site)
Un outil web est à disposition du professionnel de santé pour gérer en toute autonomie son tiers-payant. 
L’outil web de Backoffice a été développé par l’équipe de développeurs de Kozea group en collaboration avec des pharmaciens

En savoir plus (renvoi sur le site)

## Promomaker

Promomaker est un outil innovant qui permet de gérer facilement sa PLV*
en créant des affiches promotionnelles automatiquement.

Kozea group a développé Promomaker à l’aide d'un design print (lien vers http://www.gv.com/sprint/) en seulement une semaine.

Ce concepteur de PLV* est un outil simple d’utilisation pour tous les groupements et les pharmacies d’officine individuelles.
 
En savoir plus (renvoi vers le lien)

*PLV : publicité sur lieu de vente

## Kozea Media

L’agence digitale des professionnels de santé
 
Kozea media est une agence e-marketing qui conseille depuis 10 ans les différents acteurs de santé dans leur transformation digitale.

Grâce à son équipe experte en marketing digital, Kozea media accompagne les professionnels de santé pour développer une stratégie digitale performante tout en respectant les contraintes définies par ce secteur.

Du social media (community management) à la publicité on line, Kozea media propose des services sur mesure pour réussir une campagne de communication avec succès.
 
En savoir plus (renvoi sur le site www.media.kozea.fr)

**Comment by liZe** [comment]
@piline Fait sur la branche `rewrite_activity_101`.
