### ISSUE TITLE
La page de formulaire d'accès au livre blanc est faite

### ISSUE THREAD

**Issue by piline** [Kozea/www-kozea#108]
Il faut faire une page de formulaire comme sur Backoffice : https://www.lagestiondutierspayant.fr/whitepaper

Le texte est transmis par @clemenceprem 

Le lien de cette page se fera sur l'accueil. Un `li`est créé pour le téléchargement du livre blanc sur la page `index.html`.

**Comment by liZe** [comment]
Faite (https://www.kozea.fr/whitepaper).
