### ISSUE TITLE
La photo d'Alexis est retouchée 

### ISSUE THREAD

**Issue by Maxouuu** [Kozea/www-kozea#112]
Avec les caractéristiques du site internet 

Lien des photos suivantes : https://drive.google.com/drive/folders/1gCbBDWKmqGoP6IQgFKz_Rre5JQSStXw7?usp=sharing

**Comment by liZe** [comment]
@hugobernard Tu me mettrais #110 en urgent dès que c'est prêt ? Ce serait hyper gentil de ta part :cat: :dog: :tomato: :banana: :100: :1st_place_medal: :bat: :sunflower:.

**Comment by hugobernard** [comment]
https://drive.google.com/open?id=1QOaS8tOc-PqtlsBu03ph9oxAi_UuG6jx
