### ISSUE TITLE
Le site internet est à jour

### ISSUE THREAD

**Issue by Maxouuu** [Kozea/www-kozea#125]
- [x] La photo de Samira est ajoutée au site avec le titre : "Chef de projet / Développeur web"

- [x] La photo d'Alexis est remplacée par la nouvelle (son titre ne change pas)

- [x] La photo de Yohann est supprimée 

@hugobernard mettra les photos ici une fois retouchées

- [ ] rajouter le lien du site Kozea Community

**Comment by hugobernard** [comment]
Les photos d' @alexiscompta et @SamR1 sont dans ce dossier :
https://drive.google.com/open?id=1Ma2Kk01FCliLvyfUvNsFCfoHvDllYGc1

**Comment by liZe** [comment]
> Les photos d' @alexiscompta et @SamR1 sont dans ce dossier :

@hugobernard Je prends lesquelles ?

**Comment by hugobernard** [comment]
@liZe il faut demander aux intéressés directement, c'est eux qui choisissent.

**Comment by alexiscompta** [comment]
Tu peux prendre "alexis-1"
Merci
