### ISSUE TITLE
Le chat est implémenté sur le site Kozea group

### ISSUE THREAD

**Issue by JustineAnton** [Kozea/www-kozea#163]
Suite à la dernière réunion marketing et comme évoqué lors de notre point de ce jour, nous avons décidé d'ajouter sur les sites des marques le chat (comme mis en place sur le site BOS).

**Comment by ibtihalaa** [comment]
![chat-kozea](https://user-images.githubusercontent.com/55827390/195871449-b97f2a47-4872-4411-837d-8342b19dfc8c.png)
@JustineAnton
