### ISSUE TITLE
Les coquilles sont corrigées sur la page Ressources du site kozea.fr

### ISSUE THREAD

**Issue by JustineAnton** [Kozea/www-kozea#165]
Plusieurs petites choses sont à corriger sur le site : 

- [x] Le titre : ajouter un "?" à la fin de la phrase : "Comment développer vos ventes grâce à votre site internet" 
- [x] Dans la section "Données personnelles" : Enlever le "e" de groupe dans ces 2 phrases : "Les informations recueillies sur ce formulaire sont enregistrées dans un fichier informatisé par Kozea groupe pour prospecter et informer notre clientèle." et "Conformément à la loi "Informatique et Libertés", vous pouvez exercer votre droit d'accès aux données vous concernant en contactant Kozea groupe à l'adresse mail suivante : rgpd@kozea.fr"
- [x] Dans la section "Données personnelles" : mettre "sont" à la place de "sans" dans la phrase : "Elles sont conservées pendant 3 ans et sans destinées au service commercial."

**Comment by gentooboontoo** [comment]
Corrigées.
