### ISSUE TITLE
L'onglet "Contact" est déplacé dans le header du site

### ISSUE THREAD

**Issue by JustineAnton** [Kozea/www-kozea#166]
Comme vu ensemble lors de notre point vendredi dernier, le blog étant maintenant partie intégrante du site et non plus sur WordPress, il semble plus logique que celui-ci apparaisse avant les onglets À propos & Contact.
Il faudrait donc le replacer entre les onglets "Ressources" et "À propos".

**Comment by annabellou** [comment]
@gentooboontoo, j'ai regardé le fichier `_layout.html` pour intervertir les 2 éléments de la liste mais je n'ai pas compris la syntaxe utilisée, je pense que ça dépasse mes compétences 😅

        <nav class="primary center">
          <ul>
            <li class="{% if page == 'home' %}active{% endif %}"><a href="{{ url_for('home') }}">Accueil</a></li>
            {% for key, label in menu_list.items() %}
              <li class="{% if page == key %}active{% endif %}"><a href="{{ url_for(key) }}">{{ label }}</a></li>
            {% endfor %}
          </ul>
        </nav>

**Comment by gentooboontoo** [comment]
Effectivement, ce n'est pas forcément facile à identifier pour toi. Ce sont ces lignes qu'il faut modifier dans ce fichier 😉 :

https://github.com/Kozea/www-kozea/blob/782b7ebc2638da1077ce98dd119d480bcd551dc1/www_kozea/__init__.py#L6-L12

**Comment by annabellou** [comment]
@gentooboontoo, merci pour ton aide !

La modifications est faite, elle est en attente de revue avant d'être mise en ligne.

**Comment by annabellou** [comment]
C'est en ligne, je clos le ticket.
