### ISSUE TITLE
Le service Google My Business est ajouté au site

### ISSUE THREAD

**Issue by rom-rey** [Kozea/www-kozea#169]
cc @JustineAnton

Sur la page d'accueil, ajouter "Google My Business" dans le bloc "Votre communication maîtrisée et externalisée". 

![image](https://user-images.githubusercontent.com/105436734/198544630-e352af55-d0bb-4749-8d68-6aa187a0c957.png)

Dans l'onglet "Solutions", ajouter un check dans le bloc "Votre communication maîtrisée et externalisée" qui dirait "Optimisation de la fiche Google My Business".

Dans la page Kozea media, je pense qu'il faudrait rajouter un bloc indépendant pour Google My Business afin de mettre ce service en valeur sur le site. Je le mettrai juste après "gestion de réseaux sociaux". 

Ce nouveau bloc s'appellerait donc "Google My Business". Il contiendrait le picto de GMB. En description, il y aurait " Optimisation et personnalisation de votre fiche établissement Google (Google Post, modération, mise à jour)." À voir ce que Justine en pense.

J'aimerais effectivement ajouter cette information sur le site afin d'être cohérent avec la communication qui sera bientôt lancée sur le lancement du nouveau service GMB.

Il me semble donc essentiel que cette info apparaisse sur le site afin de rassurer le potentiel client sur l'existence de ce service.

@annabellou, tu me diras quand tu penses que cette tâche peut être accomplie (ne t'inquiète pas, je m'adapte à toi) afin que l'on soit synchro :)

Merciii

**Comment by JustineAnton** [comment]
Ok pour moi pour le texte et tout le reste, ça me paraît clair ! :)

**Comment by annabellou** [comment]
L'ajout du service Google My Business va donc être fait sur 3 endroits différents du site. J'ai modifié le site à la volée pour faire des captures d'écrans du résultat, ce qui permettra de valider le rendu, et de mieux définir le changements à effectuer au niveau du code.

### Page d'accueil 

![site-kozea-group-GMB-accueil](https://user-images.githubusercontent.com/7512422/199060871-bbaa0de6-8ee9-4beb-9a10-eba5bf80ee52.png)

- [ ] Le paragraphe du bloc "Votre communication maîtrisée et externalisée" est modifié pour ajouter la mention "Google My Business".

### Page Nos solutions

![site-kozea-group-GMB-solutions](https://user-images.githubusercontent.com/7512422/199061360-f1e6d164-007e-44ca-8be8-5df8c9e46ddd.png)

- [ ] Un nouvel élément est ajouté à la liste du bloc "Votre communication maîtrisée et externalisée" avec pour contenu "Optimisation de la fiche Google My Business"

### Page Kozea media

![site-kozea-group-GMB-kozea-media](https://user-images.githubusercontent.com/7512422/199061894-83a265e2-c5b6-45d3-9218-b4a01e3b4f73.png)

- [ ] Un nouveau bloc est créé, après celui de "Gestion des réseaux sociaux" : titre "Google My Business", paragraphe "Optimisation et personnalisation de votre fiche établissement Google (Google Post, modération, mise à jour")
- [ ] Ajout du pictogramme de Google My Business, avec les couleurs adaptées comme sur les autres blocs.

@rom-rey et @JustineAnton est-ce bien les résultats que vous attendiez ? Si c'est le cas, on pourra alors vous donner une idée d'échéance pour la mise en ligne de ces modifications.

**Comment by rom-rey** [comment]
C'est tout bon !

**Comment by annabellou** [comment]
J'ai fait les modifications, le code va être revu avant d'être mis en ligne, je vous tiens informées.

**Comment by annabellou** [comment]
C'est en ligne ! ✅
