### ISSUE TITLE
La mention sur la base de données produits est actualisée

### ISSUE THREAD

**Issue by AssiDir** [Kozea/www-kozea#170]
Je te remercie de bien vouloir mettre à jour les chiffres à cet emplacement.

![image](https://user-images.githubusercontent.com/50872340/198991482-59c5e5e6-4f7f-4dce-90af-ba796fece3b1.png)

https://www.kozea.fr/pharminfo/

Merci !

**Comment by gentooboontoo** [comment]
Fait. En cours de déploiement.
